import type { AggregatedReview, Issue } from "./types";

export type RenderMarkdownOptions = {
  renderEmpty?: boolean;
};

function fmtLocation(issue: Issue): string {
  const file = issue.file ? String(issue.file) : "";
  const line = issue.line ?? "?";
  if (!file) return "";
  return `\`${file}:${line}\``;
}

function fmtHeader(issue: Issue): string {
  const t = issue.type ? String(issue.type).toUpperCase() : "";
  const sev = issue.severity ? String(issue.severity).toUpperCase() : "";
  const bits = [t, sev].filter(Boolean).map((b) => `[${b}]`).join("");
  return bits ? `${bits} ` : "";
}

export function renderMarkdown(data: AggregatedReview, opts: RenderMarkdownOptions = {}): string {
  const issues = Array.isArray(data.issues) ? data.issues : [];

  if (issues.length === 0) {
    if (!opts.renderEmpty) return "";
    const threshold = data.stats?.confidence_threshold ?? "?";
    return [
      "### AI code review",
      "",
      `No issues found (threshold: ${threshold}%).`,
      "",
      "<sub>Generated by `ai-code-review`</sub>",
      "",
    ].join("\n");
  }

  const threshold = data.stats?.confidence_threshold ?? "?";
  const filteredCount = data.stats?.filtered_count ?? issues.length;
  const totalCandidates = data.stats?.total_candidates ?? "?";

  const deduped = data.stats?.duplicates_removed ?? 0;
  const dedupNote = deduped > 0 ? `, ${deduped} duplicate(s) merged` : "";

  const out: string[] = [];
  out.push("### AI code review");
  out.push("");
  out.push(
    `Found **${filteredCount}** issue(s) (filtered from ${totalCandidates} candidates, threshold: ${threshold}%${dedupNote}).`,
  );
  out.push("");

  issues.forEach((issue, idx) => {
    const title = issue.title ? String(issue.title).trim() : "";
    const loc = fmtLocation(issue);
    const conf = issue.confidence !== undefined ? `(confidence ${issue.confidence}%)` : "";
    out.push(`${idx + 1}. **${fmtHeader(issue)}${title}** ${loc} ${conf}`.trimEnd());

    const impact = issue.impact ? String(issue.impact).trim() : "";
    const recommendation = issue.recommendation ? String(issue.recommendation).trim() : "";
    const evidence = issue.evidence ? String(issue.evidence).trim() : "";

    if (impact) out.push(`   - Impact: ${impact}`);
    if (recommendation) out.push(`   - Recommendation: ${recommendation}`);
    if (evidence) out.push(`   - Evidence: ${evidence}`);

    out.push("");
  });

  out.push("<sub>Generated by `ai-code-review`</sub>");
  out.push("");
  return out.join("\n");
}

